
server:
  port: 4396
#222
#111111111111111
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true





















spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databasename=bs
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123456
  thymeleaf:
    cache: false
logging:
    level:
      com.zjc.bs.mapper: DEBUG

mapper:
  not-empty: true
  identity: SQLSERVER
  mappers: tk.mybatis.mapper.common.Mapper

pagehelper:
    helperDialect: sqlserver
    reasonable: true
    params: count=countSql
